apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health {
            lameduck 5s
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    titulo.net:53 {
        log
        errors
        cache 30
        forward . 10.30.10.11 10.40.10.11
    }
    titulo.com.br:53 {
        log
        errors
        cache 30
        forward . 10.30.10.11 10.40.10.11
    }
    easynvest.io:53 {
        log
        errors
        cache 30
        forward . 10.30.10.11 10.40.10.11
    }
    easynvest.com.br:53 {
        log
        errors
        cache 30
        forward . 10.30.10.11 10.40.10.11
    }
    bvmfnet.com.br:53 {
        log
        errors
        cache 30
        forward . 10.30.10.11 10.40.10.11
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system